# Generated by Django 5.0 on 2023-12-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='post',
        ),
        migrations.AddField(
            model_name='profile',
            name='post',
            field=models.ManyToManyField(blank=True, related_name='post', to='network.post'),
        ),
    ]
